version: "2"

services:
  fastapi:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    depends_on:
      - redis
    volumes:
      - ./app.py:/app/app.py

  redis:
    image: "redis:7.0"
